# Generated by Django 4.2.4 on 2023-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_likecomment_likepost_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likeComment',
            field=models.ManyToManyField(related_name='comment_likes', to='catalog.likecomment'),
        ),
        migrations.AddField(
            model_name='post',
            name='likePost',
            field=models.ManyToManyField(related_name='post_likes', to='catalog.likepost'),
        ),
    ]
