# Generated by Django 4.2.4 on 2023-09-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_likecomment_comment_remove_likepost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='likeComment',
            field=models.ManyToManyField(default=0, related_name='comment_likes', to='catalog.likecomment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likePost',
            field=models.ManyToManyField(default=0, related_name='post_likes', to='catalog.likepost'),
        ),
    ]
