# Generated by Django 4.2.4 on 2023-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_likecomment_comment_likepost_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
    ]
