# Generated by Django 4.2.4 on 2023-09-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_likecomment_comment_remove_likepost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likeComment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likePost',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.post'),
            preserve_default=False,
        ),
    ]
