# Generated by Django 4.2.4 on 2023-09-07 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_likecomment_comment_remove_likepost_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likeComment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likePost',
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.AddField(
            model_name='comment',
            name='likeComment',
            field=models.ManyToManyField(default=0, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likePost',
            field=models.ManyToManyField(default=0, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
