# Generated by Django 4.2.4 on 2023-09-07 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_likepost_author_remove_comment_likecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likeComment',
            field=models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likePost',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
