# Generated by Django 4.2.4 on 2023-09-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_likepost_likecomment_alter_comment_likecomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
    ]
