# Generated by Django 4.2.4 on 2023-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post1.jpg', upload_to='uploads/'),
        ),
    ]
